# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 0.12

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - cmd: npm test

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json # global npm modules
  - %APPDATA%\npm-cache -> package.json # npm cache
  - node_modules -> package.json # local npm modules
